export default {
  "login": "sansrp358",
  "id": 62197306,
  "node_id": "MDQ6VXNlcjYyMTk3MzA2",
  "avatar_url": "https://avatars0.githubusercontent.com/u/62197306?v=4",
  "gravatar_id": "",
  "url": "https://api.github.com/users/sansrp358",
  "html_url": "https://github.com/sansrp358",
  "followers_url": "https://api.github.com/users/sansrp358/followers",
  "following_url": "https://api.github.com/users/sansrp358/following{/other_user}",
  "gists_url": "https://api.github.com/users/sansrp358/gists{/gist_id}",
  "starred_url": "https://api.github.com/users/sansrp358/starred{/owner}{/repo}",
  "subscriptions_url": "https://api.github.com/users/sansrp358/subscriptions",
  "organizations_url": "https://api.github.com/users/sansrp358/orgs",
  "repos_url": "https://api.github.com/users/sansrp358/repos",
  "events_url": "https://api.github.com/users/sansrp358/events{/privacy}",
  "received_events_url": "https://api.github.com/users/sansrp358/received_events",
  "type": "User",
  "site_admin": false,
  "name": "Sanskruti Paitwar",
  "company": null,
  "blog": "",
  "location": "Mumbai",
  "email": "sansrp358@gmail.com",
  "hireable": null,
  "bio": "My objective is to work for an organization ⚡ which provide me the opportunity to improve my skills 😄 and knowledge 😄 to grow along with the organization objective ✨ and at the same time to get an opportunity for my personal development✨",
  "twitter_username": "Sanskruti",
  "public_repos": 10,
  "public_gists": 0,
  "followers": 5,
  "following": 3,
  "created_at": "2020-03-15T05:34:33Z",
  "updated_at": "2020-09-25T17:39:01Z"
};