export default [
  {
    "login": "sonali-landge",
    "id": 69230252,
    "node_id": "MDQ6VXNlcjY5MjMwMjUy",
    "avatar_url": "https://avatars3.githubusercontent.com/u/69230252?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/sonali-landge",
    "html_url": "https://github.com/sonali-landge",
    "followers_url": "https://api.github.com/users/sonali-landge/followers",
    "following_url": "https://api.github.com/users/sonali-landge/following{/other_user}",
    "gists_url": "https://api.github.com/users/sonali-landge/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/sonali-landge/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/sonali-landge/subscriptions",
    "organizations_url": "https://api.github.com/users/sonali-landge/orgs",
    "repos_url": "https://api.github.com/users/sonali-landge/repos",
    "events_url": "https://api.github.com/users/sonali-landge/events{/privacy}",
    "received_events_url": "https://api.github.com/users/sonali-landge/received_events",
    "type": "User",
    "site_admin": false
  },
  {
    "login": "g-akshay",
    "id": 8638426,
    "node_id": "MDQ6VXNlcjg2Mzg0MjY=",
    "avatar_url": "https://avatars1.githubusercontent.com/u/8638426?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/g-akshay",
    "html_url": "https://github.com/g-akshay",
    "followers_url": "https://api.github.com/users/g-akshay/followers",
    "following_url": "https://api.github.com/users/g-akshay/following{/other_user}",
    "gists_url": "https://api.github.com/users/g-akshay/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/g-akshay/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/g-akshay/subscriptions",
    "organizations_url": "https://api.github.com/users/g-akshay/orgs",
    "repos_url": "https://api.github.com/users/g-akshay/repos",
    "events_url": "https://api.github.com/users/g-akshay/events{/privacy}",
    "received_events_url": "https://api.github.com/users/g-akshay/received_events",
    "type": "User",
    "site_admin": false
  },
  {
    "login": "rohankarankot",
    "id": 70481070,
    "node_id": "MDQ6VXNlcjcwNDgxMDcw",
    "avatar_url": "https://avatars3.githubusercontent.com/u/70481070?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/rohankarankot",
    "html_url": "https://github.com/rohankarankot",
    "followers_url": "https://api.github.com/users/rohankarankot/followers",
    "following_url": "https://api.github.com/users/rohankarankot/following{/other_user}",
    "gists_url": "https://api.github.com/users/rohankarankot/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/rohankarankot/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/rohankarankot/subscriptions",
    "organizations_url": "https://api.github.com/users/rohankarankot/orgs",
    "repos_url": "https://api.github.com/users/rohankarankot/repos",
    "events_url": "https://api.github.com/users/rohankarankot/events{/privacy}",
    "received_events_url": "https://api.github.com/users/rohankarankot/received_events",
    "type": "User",
    "site_admin": false
  },
  {
    "login": "joemunene",
    "id": 70524185,
    "node_id": "MDQ6VXNlcjcwNTI0MTg1",
    "avatar_url": "https://avatars2.githubusercontent.com/u/70524185?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/joemunene",
    "html_url": "https://github.com/joemunene",
    "followers_url": "https://api.github.com/users/joemunene/followers",
    "following_url": "https://api.github.com/users/joemunene/following{/other_user}",
    "gists_url": "https://api.github.com/users/joemunene/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/joemunene/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/joemunene/subscriptions",
    "organizations_url": "https://api.github.com/users/joemunene/orgs",
    "repos_url": "https://api.github.com/users/joemunene/repos",
    "events_url": "https://api.github.com/users/joemunene/events{/privacy}",
    "received_events_url": "https://api.github.com/users/joemunene/received_events",
    "type": "User",
    "site_admin": false
  },
  {
    "login": "mrtanaji",
    "id": 52039196,
    "node_id": "MDQ6VXNlcjUyMDM5MTk2",
    "avatar_url": "https://avatars3.githubusercontent.com/u/52039196?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/mrtanaji",
    "html_url": "https://github.com/mrtanaji",
    "followers_url": "https://api.github.com/users/mrtanaji/followers",
    "following_url": "https://api.github.com/users/mrtanaji/following{/other_user}",
    "gists_url": "https://api.github.com/users/mrtanaji/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/mrtanaji/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/mrtanaji/subscriptions",
    "organizations_url": "https://api.github.com/users/mrtanaji/orgs",
    "repos_url": "https://api.github.com/users/mrtanaji/repos",
    "events_url": "https://api.github.com/users/mrtanaji/events{/privacy}",
    "received_events_url": "https://api.github.com/users/mrtanaji/received_events",
    "type": "User",
    "site_admin": false
  }
]